flaskr/views.py
from datetime import datetime

from flask import (
    Blueprint,
    abort,
    request,
    render_template,
    redirect,
    url_for,
    flash,
    session,
    jsonify,
)
from flaskr import db
from flaskr.models import Item,Brand,Category,User
from flaskr.forms import AddItemForm,EditItemForm,SearchItemForm,ToPageForm,RegisterUserForm,LoginForm
from flask_login import login_user, login_required, logout_user, current_user


bp = Blueprint("app", __name__, url_prefix="", static_folder="static")


@bp.route("/list",methods=["GET"])
def list():
    form=SearchItemForm(request.form)
    to_page_form=ToPageForm(request.form)
    items=None
    page=request.args.get("page",1,int)
    name=form.name.data=request.args.get("name","",str)
    brand=form.brand.data=request.args.get("brand","",str)
    category_path=request.args.get("category_path","",str)
    parent=category_path.split("/")[0] if category_path!="" else request.args.get("parent_category","",str)
    child=category_path.split("/")[1] if category_path!="" else request.args.get("child_category","",str)
    grand_child=category_path.split("/")[2] if category_path!="" else request.args.get("grand_child_category","",str)
    if category_path=="":
        if parent=="":
            category_path=""
        elif child=="":
            category_path=f"{parent}/"
        elif grand_child=="":
            category_path=f"{parent}/{child}/"
        else:
            category_path=f"{parent}/{child}/{grand_child}/"
        
    items=Item.get_list(name,category_path,brand,page)
    form.parent_category.choices = [(parent, parent)] if parent!="" else [("", "--parentCategory--")]
    form.child_category.choices = [(child, child)] if child!="" else [("", "--childCategory--")]
    form.grand_child_category.choices = [(grand_child, grand_child)] if grand_child!="" else [("", "--grandChild--")]
    
    next_page=url_for("app.list",name=name,category_path=category_path,brand=brand,page=items.next_num)
    prev_page=url_for("app.list",name=name,category_path=category_path,brand=brand,page=items.prev_num)
    
       
    return render_template("list.html",items=items,form=form,to_page_form=to_page_form,
                           next_page=next_page,prev_page=prev_page,category_path=category_path)


@bp.route("/detail/<int:item_id>",methods=["GET","POST"])
def detail(item_id):
    item=Item.load_item(item_id)
    return render_template("detail.html",item=item)

@bp.route("/add",methods=["GET","POST"])
@login_required
def add():
    form=AddItemForm(request.form)
    if request.method=="POST" and form.validate():
        brand_id=Brand.select_brand_by_name(form.brand.data).brand_id
        item=Item(form.name.data,form.condition.data,form.grand_child_category.data,brand_id,form.price.data,form.description.data)
        item_id=item.create_new_item()
        return redirect(url_for("app.detail",item_id=item_id))
    return render_template("add.html",form=form)

@bp.route("/edit/<int:item_id>",methods=["GET","POST"])
@login_required
def edit(item_id):
    form=EditItemForm(request.form)
    
    if request.method=="POST" and form.validate():
        brand_id=Brand.select_brand_by_name(form.brand.data).brand_id
        item=Item(form.name.data,form.condition.data,form.grand_child_category.data,brand_id,form.price.data,form.description.data)
        item.update_item(item_id)
        return redirect(url_for("app.detail",item_id=item_id))
    
    item=Item.load_item(item_id)
    # カテゴリプルダウンにカテゴリ名を入れる
    categories=item.path.split("/")
    form.parent_category.choices = [(categories[0], categories[0])]
    form.child_category.choices = [(categories[1], categories[1])]
    form.grand_child_category.choices = [(item.category_id, categories[2])]
    
    # ラジオボタンにチェックを入れる
    form.condition.default=item.condition_id
    form.process()
    
    # テキストエリアに説明文を入れる
    form.description.process_data(item.description)
    
    return render_template("edit.html",item=item,form=form)
    


@bp.route("/get_parent_category",methods=["GET","POST"])
def get_parent_category():
    result=Category.get_parent_category()
    categories=[]
    for category in result:
        detail={"id":category.category_id,"name":category.name} 
        categories.append(detail)    
    return jsonify(data=categories)


@bp.route("/get_child_category",methods=["GET","POST"])
def get_child_category():
    parent_name=request.args.get("path",type=str)
    hierarchy=request.args.get("hierarchy",type=int)
    result=Category.get_child_category(parent_name,hierarchy)
    categories=[]
    for category in result:
        detail={"id":category.category_id,"name":category.name} 
        categories.append(detail)    
    return jsonify(data=categories)


@bp.route("/register",methods=["GET","POST"])
def register():
    form=RegisterUserForm(request.form)
    if request.method=="POST" and form.validate():
        user=User(form.name.data,form.mail_address.data,form.password.data,1)
        user.password_hash()
        user.create_new_user()
        return redirect("app.login")
    return render_template("register.html",form=form)

@bp.route("/login",methods=["GET","POST"])
def login():
    form=LoginForm(request.form)
    
    if request.method=="POST":
        user=User.select_user_by_mail_address(form.mail_address.data)
        if user and user.check_password(form.password.data):
            login_user(user, remember=True)
            next = request.args.get("next") if request.args.get("next") else url_for("app.list")
            return redirect(next)
        else:
            flash("Email address or password is incorrect")    
    
    return render_template("login.html",form=form)


@bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("app.login"))

flaskr/templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
    <label class="col-sm-2 control-label">{{ field.label }}</label>
    <div class="col-sm-8">
        {{ field(**kwargs) | safe }}
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
            <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </ul>
        {% endif %}
      </div>
</div>
{% endmacro %}

flaskr/templates/add.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block content %}

  <!-- details -->
  <div id="input-main" class="container">
    <a type="button" class="btn btn-default" href="./list.html"><i class="fa fa-reply"></i> back</a>
    <h2>Add</h2>

    <!-- add form -->
    <form method="POST" class="form-horizontal">
      {{ form.csrf_token }}
      <!-- name -->
      {{ render_field(form.name,class="form-control") }}
      <!-- price -->
      {{ render_field(form.price,class="form-control") }}
      <!-- category -->
      {{ render_field(form.parent_category,class="form-control") }}
      {{ render_field(form.child_category,class="form-control") }}
      {{ render_field(form.grand_child_category,class="form-control") }}
      <!-- brand -->
      {{ render_field(form.brand,class="form-control") }}
      <!-- condition -->
      {{ render_field(form.condition,class="radio-inline") }}
      <!-- description -->
      {{ render_field(form.description,class="form-control") }}
      <!-- submit button -->
      {{ render_field(form.submit,class="btn btn-default") }}
    </form>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
	<script src="../static/js/category.js"></script>
{% endblock %}

flaskr/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <!-- css -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" 
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"/>
  <link rel="stylesheet" href="../static/css/mercari.css"/>
  <!-- script -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <title>Rakus Items</title>
</head>
<body>
  <!-- navbar -->
  <nav class="navbar navbar-inverse">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.list') }}">Rakus Items</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <div>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li><a id="logout" href="{{ url_for('app.logout') }}">Logout&nbsp;<i class="fa fa-power-off"></i></a></li>
          {% else %}
          <li><a id="logout" href="{{ url_for('app.login') }}">Login&nbsp;<i class="fa fa-power-off"></i></a></li>
          {% endif %}
        </ul>
        {% if current_user.is_authenticated %}
        <p class="navbar-text navbar-right">
          <span id="loginName">user: {{ current_user.name }}</span>
        </p>
        {% endif %}
      </div>
    </div>
  </nav>
  {% block content %}

  {% endblock %}
</body>
</html>

flaskr/templates/detail.html
{% extends "base.html" %}
{% block content %}
  <!-- details -->
  <div class="container">
    <a type="button" class="btn btn-default" href="./list.html"><i class="fa fa-reply"></i> back</a>
    <h2>Details</h2>
    <div id="details">
      <table class="table table-hover">
        <tbody>
          <tr>
            <th>ID</th>
            <td>{{ item.id }}</td>
          </tr>
          <tr>
            <th>name</th>
            <td>{{ item.name }}</td>
          </tr>
          <tr>
            <th>price</th>
            <td>${{ item.price }}</td>
          </tr>
          <tr>
            <th>category</th>
            <td>{{ item.path }}</td>
          </tr>
          <tr>
            <th>brand</th>
            <td>{{ item.brand_name }}</td>
          </tr>
          <tr>
            <th>condition</th>
            <td>{{ item.condition_id }}</td>
          </tr>
          <tr>
            <th>description</th>
            <td>{{ item.description }}</td>
          </tr>
        </tbody>
      </table>
      <a type="submit" class="btn btn-default" href="{{ url_for('app.edit',item_id=item.id) }}"><i class="fa fa-pencil-square-o"></i>&nbsp;edit</a>
    </div>
  </div>
{% endblock %}

flaskr/templates/edit.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block content %}

  <!-- details -->
  <div id="input-main" class="container">
    <a type="button" class="btn btn-default" href="./detail.html"><i class="fa fa-reply"></i> back</a>
    <h2>Edit</h2>

    <!-- edit form -->
    <form method="POST" class="form-horizontal">
      {{ form.csrf_token }}
      {{ form.id(value=item.id) }}
      <!-- name -->
      {{ render_field(form.name,class="form-control",value=item.name) }}
      <!-- price -->
      {{ render_field(form.price,class="form-control",value=item.price) }}
      <!-- category -->
      {{ render_field(form.parent_category,class="form-control") }}
      {{ render_field(form.child_category,class="form-control") }}
      {{ render_field(form.grand_child_category,class="form-control") }}
      <!-- brand -->
      {{ render_field(form.brand,class="form-control",value=item.brand_name) }}
      <!-- condition -->
      {{ render_field(form.condition,class="radio-inline",checked=item.condition_id) }}
      <!-- description -->
      {{ render_field(form.description,class="form-control",value=item.description) }}
      <!-- submit button -->
      {{ render_field(form.submit,class="btn btn-default") }}
    </form>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
	<script src="../static/js/category.js"></script>
{% endblock %}

flaskr/templates/list.html
{% extends "base.html" %}
{% block content %}
  <div id="main" class="container-fluid">
    <!-- addItem link -->
    <div id="addItemButton">
      <a class="btn btn-default" href="{{ url_for('app.add') }}"><i class="fa fa-plus-square-o"></i> Add New Item</a>
    </div>

    <!-- 検索フォーム -->
    <div id="forms">
      <form method="GET" class="form-inline" role="form">
        <div class="form-group">
          {{ form.name(class="form-control",placeholder="item name") }}
        </div>
        <div class="form-group"><i class="fa fa-plus"></i></div>
        <div class="form-group">
          {{ form.parent_category(class="form-control") }}
          {{ form.child_category(class="form-control") }}
          {{ form.grand_child_category(class="form-control") }}
        </div>
        <div class="form-group"><i class="fa fa-plus"></i></div>
        <div class="form-group">
          {{ form.brand(class="form-control",placeholder="brand") }}
        </div>
        <div class="form-group"></div>
        {{ form.submit(class="btn btn-default") }}
      </form>
    </div>

    <!-- pagination -->
    <div class="pages">
      <nav class="page-nav">
        <ul class="pager">
          {% if items.prev_num!=None %}
          <li class="previous"><a href="{{ prev_page }}">&larr; prev</a></li>
          {% endif %}
          {% if items.next_num!=None %}
          <li class="next"><a href="{{ next_page | safe }}">next &rarr;</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>

    <!-- table -->
    <div class="table-responsive">
      <table id="item-table" class="table table-hover table-condensed">
        <thead>
          <tr>
            <th>name</th>
            <th>price</th>
            <th>category</th>
            <th>brand</th>
            <th>cond</th>
          </tr>
        </thead>
        <tbody>
          {% for item in items.items %}
          <tr>
            <td class="item-name"><a href="{{ url_for('app.detail',item_id=item.id) }}">{{ item.name }}</a></td>
            <td class="item-price">{{ item.price }}</td>
            <td class="item-category">{{ item.path }}</td>
            <td class="item-brand">{{ item.brand_name }}</td>
            <td class="item-condition">
              {% for condition in [(1,"Mint"),(2,"Near Mint"),(3,"Excellent"),(4,"Very Good"),(5,"Good")] %}
              {% if condition[0]==item.condition_id %}
              {{ condition[1] }}
              {% endif %}
              {% endfor %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <!-- pagination -->
    <div class="pages">
      <nav class="page-nav">
        <ul class="pager">
          {% if items.prev_num!=None %}
          <li class="previous"><a href="{{ prev_page }}">&larr; prev</a></li>
          {% endif %}
          {% if items.next_num!=None %}
          <li class="next"><a href="{{ next_page | safe }}">next &rarr;</a></li>
          {% endif %}
        </ul>
      </nav>
      <!-- ページ番号を指定して表示するフォーム -->
      <div id="select-page">
        <form method="GET" class="form-inline">
          <div class="form-group">
            <div class="input-group col-xs-6">
              {{ to_page_form.page(class="form-control",value=items.page) }}
              {{ to_page_form.name(value=form.name.data) }}
              {{ to_page_form.brand(value=form.brand.data) }}
              {{ to_page_form.category_path(value=category_path) }}
              <!-- 総ページ数 -->
              <div class="input-group-addon">/ {{ items.pages }}</div>
            </div>
            <div class="input-group col-xs-1">
              {{ to_page_form.submit(class="btn btn-default") }}
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
	<script src="../static/js/search.js"></script>
{% endblock %}

flaskr/templates/login.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block content %}
  <!-- login form -->
  <div id="login" class="container">
    <div class="panel panel-default">
      <div class="panel-heading">Login</div>
      <div class="panel-body">
        {% for message in get_flashed_messages() %}
        <p class="text-danger">{{ message }}</p>
        {% endfor %}
        <form method="POST" class="form-horizontal">
          {{ form.csrf_token }}
          {{ render_field(form.mail_address,class="form-control") }}
          {{ render_field(form.password,class="form-control") }}
          {{ form.submit(class="btn btn-default") }}
        </form>
      </div>
    </div>
    <div>
      <a type="button" class="btn btn-default" href="./register.html"><i class="fa fa-user-plus"></i>&nbsp;Register Account</a>
    </div>
  </div>
{% endblock %}

flaskr/templates/register.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block content %}
  <!-- register form -->
  <div id="login" class="container">
    <div class="panel panel-default">
      <div class="panel-heading">Register Account</div>
      <div class="panel-body">
        <form method="POST" class="form-horizontal">
          {{ form.csrf_token }}
          {{ render_field(form.name,class="form-control") }}
          {{ render_field(form.mail_address,class="form-control") }}
          {{ render_field(form.password,class="form-control") }}
          {{ render_field(form.confirm_password,class="form-control") }}
          {{ render_field(form.submit,class="btn btn-default") }}
        </form>
      </div>
    </div>
    <div>
      <a type="button" class="btn btn-default" href="./login.html"><i class="fa fa-reply"></i>&nbsp;Login page</a>
    </div>
{% endblock %}